version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: sitti
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: simple-restful
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    # image: node
    build: .
    volumes:
      - .:/usr/src/app/
      - dependencies:/usr/src/app/node_modules
    working_dir: /usr/src/app
    depends_on:
      - db
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    command: npm run start
volumes:
  db_data:
  dependencies:
